#!/bin/bash
# Push container image to geerlingguy.php-apache Docker Hub repository.

# Log into Docker Hub.
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# Push $php_version tag.
docker push heremias/php-apache:${php_version}

# Push $php_version + '.x' tag.
docker tag heremias/php-apache:${php_version} heremias/php-apache:${php_version}.x
docker push heremias/php-apache:${php_version}.x

# Push $php_version + '.PHP_RELEASE_VERSION' tag.
php_release_version=$(docker run --rm heremias/php-apache:${php_version} bash -c "php -r 'echo PHP_RELEASE_VERSION;'")
docker tag heremias/php-apache:${php_version} heremias/php-apache:${php_version}.${php_release_version}
docker push heremias/php-apache:${php_version}.${php_release_version}

# Push latest tag if building latest version.
if [[ "$php_version" == "7.4" ]]; then
  docker tag heremias/php-apache:${php_version} heremias/php-apache:latest
  docker push heremias/php-apache:latest
fi
